"use client";
import { useAuth } from "@clerk/nextjs";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";

interface Report {
  id: string;
  tool: "gap-analysis" | "stack-advisor";
  idea: string;
  created_at: string;
  json_content: string;
}

export default function ReportsPage() {
  const { isSignedIn, isLoaded } = useAuth();
  const router = useRouter();
  const [reports, setReports] = useState<Report[]>([]);
  const [loading, setLoading] = useState(true);
  const [deleting, setDeleting] = useState<string | null>(null);

  useEffect(() => {
    if (!isLoaded) return;
    if (!isSignedIn) { router.push("/"); return; }
    fetch("/api/reports")
      .then(r => r.json())
      .then(d => setReports(d.reports ?? []))
      .catch(() => {})
      .finally(() => setLoading(false));
  }, [isSignedIn, isLoaded, router]);

  const handleDelete = async (id: string) => {
    setDeleting(id);
    await fetch("/api/reports", { method: "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id }) });
    setReports(r => r.filter(x => x.id !== id));
    setDeleting(null);
  };

  const handleDownload = (report: Report) => {
    // Build a styled HTML page for printing
    const toolLabel = report.tool === "gap-analysis" ? "Gap Analysis" : "Stack Advisor";
    const date = new Date(report.created_at).toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" });

    // Parse JSON to extract key info
    let parsed: Record<string, unknown> = {};
    try {
      const match = report.json_content.match(/```json\s*([\s\S]*?)```/);
      parsed = JSON.parse(match ? match[1] : report.json_content);
    } catch {}

    const html = `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>${toolLabel} — ${report.idea}</title>
<style>
  body { font-family: system-ui, sans-serif; color: #111; max-width: 800px; margin: 0 auto; padding: 40px 32px; line-height: 1.6; }
  h1 { font-size: 22px; font-weight: 700; margin-bottom: 4px; }
  .meta { color: #6b7280; font-size: 13px; margin-bottom: 32px; }
  .badge { display: inline-block; background: #eff6ff; color: #1d4ed8; padding: 2px 8px; border-radius: 4px; font-size: 11px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.05em; margin-right: 8px; }
  h2 { font-size: 14px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.07em; color: #374151; margin: 24px 0 8px; border-bottom: 1px solid #e5e7eb; padding-bottom: 4px; }
  p { margin: 0 0 12px; font-size: 14px; }
  ul { margin: 0 0 12px; padding-left: 20px; font-size: 14px; }
  li { margin-bottom: 4px; }
  .score { font-size: 36px; font-weight: 800; color: #6366f1; }
  @media print { body { padding: 20px; } }
</style>
</head>
<body>
<div class="meta"><span class="badge">${toolLabel}</span>${date}</div>
<h1>${report.idea}</h1>
${parsed.marketScore ? `<p><span class="score">${parsed.marketScore}</span><span style="color:#9ca3af; font-size:18px">/100</span></p>` : ""}
${parsed.marketScoreSummary ? `<p>${parsed.marketScoreSummary}</p>` : ""}
${parsed.oneLiner ? `<h2>One-Liner</h2><p style="font-style:italic">"${parsed.oneLiner}"</p>` : ""}
${parsed.synthesis && typeof parsed.synthesis === "object" && (parsed.synthesis as Record<string, unknown>).oneParagraph ? `<h2>Synthesis</h2><p>${(parsed.synthesis as Record<string, string>).oneParagraph}</p>` : ""}
${Array.isArray(parsed.marketGaps) ? `<h2>Market Gaps</h2><ul>${(parsed.marketGaps as {title: string; description: string}[]).map(g => `<li><strong>${g.title}</strong> — ${g.description}</li>`).join("")}</ul>` : ""}
${Array.isArray(parsed.competitors) ? `<h2>Competitors</h2><ul>${(parsed.competitors as {name: string; tagline: string}[]).map(c => `<li><strong>${c.name}</strong> — ${c.tagline}</li>`).join("")}</ul>` : ""}
${Array.isArray(parsed.painPoints) ? `<h2>Pain Points</h2><ul>${(parsed.painPoints as {quote: string; source: string}[]).map(p => `<li>"${p.quote}" <em>(${p.source})</em></li>`).join("")}</ul>` : ""}
<p style="margin-top:40px; color:#9ca3af; font-size:12px; border-top:1px solid #e5e7eb; padding-top:16px">Generated by Unbuilt.me — ${date}</p>
</body>
</html>`;

    const blob = new Blob([html], { type: "text/html" });
    const url = URL.createObjectURL(blob);
    const win = window.open(url, "_blank");
    if (win) {
      win.onload = () => {
        setTimeout(() => { win.print(); URL.revokeObjectURL(url); }, 500);
      };
    }
  };

  const toolColor = (tool: string) => tool === "gap-analysis" ? "#7c6fff" : "#38bdf8";
  const toolLabel = (tool: string) => tool === "gap-analysis" ? "Gap Analysis" : "Stack Advisor";

  return (
    <div style={{ padding: "32px 40px", maxWidth: 900, margin: "0 auto" }}>
      <div style={{ marginBottom: 28 }}>
        <div style={{ fontSize: 11, fontWeight: 700, textTransform: "uppercase", letterSpacing: "0.08em", color: "var(--clr-text-4)", marginBottom: 6 }}>My Reports</div>
        <h1 style={{ fontSize: 22, fontWeight: 700, color: "var(--clr-text)", margin: 0 }}>Your analyses</h1>
        <p style={{ fontSize: 14, color: "var(--clr-text-3)", marginTop: 6 }}>Every Gap Analysis and Stack Advisor report you've run.</p>
      </div>

      {loading && (
        <div style={{ padding: "48px 0", textAlign: "center", color: "var(--clr-text-4)", fontSize: 14 }}>Loading…</div>
      )}

      {!loading && reports.length === 0 && (
        <div style={{ padding: "64px 32px", textAlign: "center", border: "1px dashed var(--clr-border)", borderRadius: 12, color: "var(--clr-text-4)" }}>
          <div style={{ fontSize: 32, marginBottom: 12, opacity: 0.4 }}>
            <svg width="40" height="40" viewBox="0 0 40 40" fill="none" style={{ margin: "0 auto", display: "block" }}><path d="M8 6h16l8 8v22H8V6z" stroke="currentColor" strokeWidth="2" strokeLinejoin="round"/><path d="M24 6v8h8" stroke="currentColor" strokeWidth="2"/><path d="M13 20h14M13 27h10" stroke="currentColor" strokeWidth="2" strokeLinecap="round"/></svg>
          </div>
          <div style={{ fontSize: 15, fontWeight: 600, color: "var(--clr-text-2)", marginBottom: 6 }}>No reports yet</div>
          <div style={{ fontSize: 13, color: "var(--clr-text-4)" }}>Run a Gap Analysis or Stack Advisor to get started.</div>
        </div>
      )}

      {!loading && reports.length > 0 && (
        <div style={{ display: "flex", flexDirection: "column", gap: 0, border: "1px solid var(--clr-border)", borderRadius: 12, overflow: "hidden", background: "var(--clr-surface)" }}>
          {/* Header row */}
          <div style={{ display: "grid", gridTemplateColumns: "1fr 120px 140px 120px 36px", gap: 0, padding: "10px 20px", background: "var(--clr-surface-2)", borderBottom: "1px solid var(--clr-border)" }}>
            {["Idea", "Tool", "Date", "", ""].map((h, i) => (
              <div key={i} style={{ fontSize: 11, fontWeight: 700, textTransform: "uppercase", letterSpacing: "0.07em", color: "var(--clr-text-4)" }}>{h}</div>
            ))}
          </div>

          {reports.map((report, i) => (
            <div key={report.id} style={{ display: "grid", gridTemplateColumns: "1fr 120px 140px 120px 36px", gap: 0, alignItems: "center", padding: "14px 20px", borderBottom: i < reports.length - 1 ? "1px solid var(--clr-border)" : "none", transition: "background 0.1s" }}
              onMouseEnter={e => (e.currentTarget as HTMLElement).style.background = "var(--clr-surface-2)"}
              onMouseLeave={e => (e.currentTarget as HTMLElement).style.background = ""}
            >
              {/* Idea */}
              <div style={{ fontSize: 14, fontWeight: 500, color: "var(--clr-text)", overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap", paddingRight: 16 }}>
                {report.idea}
              </div>

              {/* Tool badge */}
              <div>
                <span style={{ fontSize: 10, fontWeight: 700, textTransform: "uppercase", letterSpacing: "0.05em", padding: "3px 8px", borderRadius: 5, background: `${toolColor(report.tool)}18`, color: toolColor(report.tool) }}>
                  {toolLabel(report.tool)}
                </span>
              </div>

              {/* Date */}
              <div style={{ fontSize: 13, color: "var(--clr-text-3)" }}>
                {new Date(report.created_at).toLocaleDateString("en-GB", { day: "numeric", month: "short", year: "numeric" })}
              </div>

              {/* Download */}
              <div>
                <button
                  onClick={() => handleDownload(report)}
                  style={{ display: "flex", alignItems: "center", gap: 6, padding: "6px 12px", borderRadius: 7, border: "1px solid var(--clr-border)", background: "transparent", color: "var(--clr-text-2)", fontSize: 12, fontWeight: 600, cursor: "pointer", fontFamily: "inherit", transition: "background 0.1s" }}
                  onMouseEnter={e => (e.currentTarget as HTMLButtonElement).style.background = "var(--clr-surface-2)"}
                  onMouseLeave={e => (e.currentTarget as HTMLButtonElement).style.background = "transparent"}
                >
                  <svg width="12" height="12" viewBox="0 0 16 16" fill="none"><path d="M8 2v8M5 7l3 3 3-3" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round"/><path d="M3 11v1.5A1.5 1.5 0 004.5 14h7a1.5 1.5 0 001.5-1.5V11" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round"/></svg>
                  PDF
                </button>
              </div>

              {/* Delete */}
              <div>
                <button
                  onClick={() => handleDelete(report.id)}
                  disabled={deleting === report.id}
                  style={{ width: 28, height: 28, display: "flex", alignItems: "center", justifyContent: "center", borderRadius: 6, border: "none", background: "transparent", cursor: "pointer", opacity: deleting === report.id ? 0.4 : 0.5, transition: "opacity 0.1s, background 0.1s" }}
                  onMouseEnter={e => { (e.currentTarget as HTMLButtonElement).style.opacity = "1"; (e.currentTarget as HTMLButtonElement).style.background = "rgba(239,68,68,0.08)"; }}
                  onMouseLeave={e => { (e.currentTarget as HTMLButtonElement).style.opacity = "0.5"; (e.currentTarget as HTMLButtonElement).style.background = "transparent"; }}
                >
                  <svg width="13" height="13" viewBox="0 0 16 16" fill="none"><path d="M3 4h10M6 4V2.5h4V4M5 4v8.5A1.5 1.5 0 006.5 14h3A1.5 1.5 0 0011 12.5V4" stroke="#ef4444" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round"/></svg>
                </button>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
