const S = ({ children, style, ...props }: React.HTMLAttributes<HTMLElement> & { as?: string }) => (
  <section style={{ marginBottom: "2.5rem", ...style }} {...props}>{children}</section>
);
const H2 = ({ children }: { children: React.ReactNode }) => (
  <h2 style={{ fontSize: 20, fontWeight: 600, color: "#fff", marginBottom: "0.75rem", letterSpacing: "-0.01em" }}>{children}</h2>
);
const P = ({ children }: { children: React.ReactNode }) => (
  <p style={{ color: "#bbb", marginBottom: "0.75rem" }}>{children}</p>
);
const UL = ({ children }: { children: React.ReactNode }) => (
  <ul style={{ color: "#bbb", paddingLeft: "1.25rem", marginBottom: "0.75rem", listStyleType: "disc" }}>{children}</ul>
);
const LI = ({ children }: { children: React.ReactNode }) => (
  <li style={{ marginBottom: "0.35rem" }}>{children}</li>
);

export default function TermsOfServicePage() {
  return (
    <>
      <S>
        <P>
          Welcome to Unbuilt. By accessing or using our service, you agree to be bound by these Terms of Service. If you do not agree with any part of these terms, please do not use the service.
        </P>
      </S>

      <S>
        <H2>1. Service Description</H2>
        <P>
          Unbuilt is a market research platform that uses artificial intelligence and public data sources to generate market analysis, competitor insights, trend reports, and gap assessments. The service is provided &quot;as-is&quot; for market research and informational purposes.
        </P>
      </S>

      <S>
        <H2>2. AI-Generated Content Disclaimer</H2>
        <P>
          <strong style={{ color: "#fff" }}>All analysis and content generated by Unbuilt is for informational purposes only.</strong> It should not be construed as financial advice, investment advice, legal advice, or any other form of professional counsel.
        </P>
        <P>
          AI-generated insights are based on publicly available data and algorithmic analysis. While we strive for accuracy, we make no guarantees about the completeness, reliability, or timeliness of any analysis. You should independently verify any information before making business decisions.
        </P>
      </S>

      <S>
        <H2>3. Acceptable Use</H2>
        <P>You agree not to:</P>
        <UL>
          <LI>Abuse, overload, or attempt to disrupt the service or its infrastructure</LI>
          <LI>Scrape, crawl, or use automated tools to extract data from the service</LI>
          <LI>Reverse engineer, decompile, or attempt to extract source code from the service</LI>
          <LI>Use the service to generate content that is illegal, harmful, or violates third-party rights</LI>
          <LI>Share your account credentials with unauthorized parties</LI>
          <LI>Resell or redistribute analysis results as your own commercial data product</LI>
          <LI>Circumvent any rate limits, access controls, or security measures</LI>
        </UL>
      </S>

      <S>
        <H2>4. Intellectual Property</H2>
        <P>
          The Unbuilt platform, including its design, code, and branding, is owned by Unbuilt. Analysis results generated for you may be used for your own business purposes, but the underlying platform and methodology remain our intellectual property.
        </P>
      </S>

      <S>
        <H2>5. Third-Party Data</H2>
        <P>
          Our service aggregates data from third-party sources including Apple App Store, Google Play, Product Hunt, GitHub, YouTube, and others. This data is subject to the respective terms and policies of those platforms. We are not responsible for the accuracy or availability of third-party data.
        </P>
      </S>

      <S>
        <H2>6. Service Availability</H2>
        <P>
          We aim to provide reliable service but do not guarantee uninterrupted availability. The service may be temporarily unavailable due to maintenance, updates, or circumstances beyond our control. We reserve the right to modify, suspend, or discontinue the service at any time.
        </P>
      </S>

      <S>
        <H2>7. Limitation of Liability</H2>
        <P>
          To the maximum extent permitted by law, Unbuilt shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including loss of profits, data, or business opportunities, arising from your use of the service.
        </P>
      </S>

      <S>
        <H2>8. Account Termination</H2>
        <P>
          We reserve the right to suspend or terminate your account if you violate these terms. You may also delete your account at any time by contacting us. Upon termination, your right to use the service ceases immediately.
        </P>
      </S>

      <S>
        <H2>9. Changes to These Terms</H2>
        <P>
          We may update these Terms of Service from time to time. Continued use of the service after changes constitutes acceptance of the new terms. We will make reasonable efforts to notify users of material changes.
        </P>
      </S>

      <S>
        <H2>10. Contact</H2>
        <P>
          If you have any questions about these Terms of Service, please contact us at{" "}
          <a href="mailto:builder@unbuilt.me" style={{ color: "#888", textDecoration: "underline", textUnderlineOffset: 3 }}>builder@unbuilt.me</a>.
        </P>
      </S>
    </>
  );
}
