const S = ({ children }: { children: React.ReactNode }) => (
  <section style={{ marginBottom: "2.5rem" }}>{children}</section>
);
const H2 = ({ children }: { children: React.ReactNode }) => (
  <h2 style={{ fontSize: 20, fontWeight: 600, color: "var(--clr-text)", marginBottom: "0.75rem", letterSpacing: "-0.01em" }}>{children}</h2>
);
const P = ({ children }: { children: React.ReactNode }) => (
  <p style={{ color: "var(--clr-text)", marginBottom: "0.75rem" }}>{children}</p>
);
const UL = ({ children }: { children: React.ReactNode }) => (
  <ul style={{ paddingLeft: "1.5rem", marginBottom: "0.75rem", color: "var(--clr-text)", lineHeight: 1.8 }}>{children}</ul>
);
const LI = ({ children }: { children: React.ReactNode }) => <li>{children}</li>;
const B = ({ children }: { children: React.ReactNode }) => <strong style={{ fontWeight: 600 }}>{children}</strong>;
const A = ({ href, children }: { href: string; children: React.ReactNode }) => (
  <a href={href} style={{ color: "var(--clr-accent)", textDecoration: "underline" }}>{children}</a>
);
const OL = ({ children }: { children: React.ReactNode }) => (
  <ol style={{ paddingLeft: "1.5rem", marginBottom: "0.75rem", color: "var(--clr-text)", lineHeight: 1.8 }}>{children}</ol>
);

export default function TermsPage() {
  return (
    <>
      <S><H2>1. Operator</H2><P>unbuilt.me (the &ldquo;Service&rdquo;) is operated by an independent developer based in Türkiye (&ldquo;we,&rdquo; &ldquo;us,&rdquo; &ldquo;our&rdquo;).</P><P>By accessing or using the Service, you agree to these Terms of Service (&ldquo;Terms&rdquo;). If you do not agree, do not use the Service.</P></S>

      <S><H2>2. Eligibility</H2><P>You may use the Service only if you can legally enter into a binding contract under applicable law.</P><P>If you use the Service on behalf of a company, organization, or other entity, you represent and warrant that you have authority to bind that entity to these Terms.</P></S>

      <S><H2>3. Description of the Service</H2><P>The Service provides software tools and AI-generated outputs related to, among other things:</P><UL><LI>startup or business idea analysis,</LI><LI>market and competitor analysis,</LI><LI>technology stack suggestions,</LI><LI>build planning,</LI><LI>launch and product discovery,</LI><LI>related reports, summaries, exports, and gated features.</LI></UL><P>The Service may include free features, paid subscription features, paid add-on usage, saved reports, exports, and other gated or limited-access functionality.</P><P>The Service is a digital, non-tangible, software-as-a-service offering delivered on demand over the internet.</P></S>

      <S><H2>4. AI Output Disclaimer</H2><P>The Service uses artificial intelligence and automated systems to generate outputs.</P><P>You acknowledge and agree that:</P><UL><LI>outputs may be inaccurate, incomplete, inconsistent, misleading, outdated, or not fit for your intended purpose;</LI><LI>outputs are generated probabilistically and may contain errors, omissions, hallucinations, or faulty reasoning;</LI><LI>outputs do not constitute financial, investment, legal, tax, accounting, employment, medical, or other professional advice;</LI><LI>outputs are provided for informational and experimental purposes only;</LI><LI>you are solely responsible for reviewing, verifying, and evaluating any output before relying on it; and</LI><LI>all decisions, actions, omissions, investments, purchases, launches, product choices, business strategies, or legal/commercial consequences resulting from your use of the Service are solely your responsibility.</LI></UL><P>We do not guarantee that any output is accurate, useful, complete, merchantable, profitable, lawful, non-infringing, or suitable for any specific use case.</P></S>

      <S><H2>5. No Guarantee of Outcomes</H2><P>We do not guarantee:</P><UL><LI>that a business idea will succeed or fail,</LI><LI>that an analysis is correct,</LI><LI>that a stack recommendation is appropriate,</LI><LI>that a report will improve your decision-making,</LI><LI>that any product will launch successfully,</LI><LI>that any market opportunity exists,</LI><LI>or that use of the Service will produce revenue, customers, investment, savings, or business results.</LI></UL><P>The Service may be useful, but it is not a guarantee, certification, endorsement, or prediction engine.</P></S>

      <S><H2>6. Free and Paid Access</H2><P>We may offer both free and paid access to the Service.</P><P>Free access may include limited outputs, limited daily usage, reduced model quality, reduced data depth, gated sections, blurred or locked content, disabled exports, disabled saved reports, and other restrictions.</P><P>Paid access may include subscriptions, included monthly analyses, add-on analyses, deeper outputs, higher-quality model usage, broader report access, saved reports, exports, and other premium features.</P><P>We may add, remove, change, gate, limit, or discontinue any feature, entitlement, quota, or access level at any time.</P></S>

      <S><H2>7. Analyses, Quotas, and Usage Limits</H2><P>Certain features are measured using analyses or other internal usage units.</P><P>You agree that:</P><UL><LI>an analysis is a digital usage entitlement within the Service;</LI><LI>analyses have no cash value, are not property, are not transferable, and are not redeemable outside the Service;</LI><LI>different features may consume different numbers of analyses;</LI><LI>we may change what counts as an analysis, how analyses are consumed, and which features require analyses;</LI><LI>free usage may be subject to per-day, per-IP, per-account, per-device, or other rate limits;</LI><LI>we may apply anti-abuse controls, throttling, gating, or usage restrictions at any time.</LI></UL><P>If your included monthly analyses are exhausted, we may downgrade your experience to the free or limited version unless you purchase additional analyses or your subscription renews.</P><P>We reserve the right to refuse, throttle, suspend, block, or invalidate usage we believe is abusive, automated, fraudulent, manipulative, or in violation of these Terms.</P></S>

      <S><H2>8. Subscription Plans</H2><P>If you purchase a subscription plan:</P><UL><LI>your subscription may renew automatically on a recurring basis unless canceled before renewal;</LI><LI>your subscription may include a fixed number of monthly analyses per billing cycle;</LI><LI>included monthly analyses, if any, do not carry over unless we expressly state otherwise;</LI><LI>included monthly analyses may reset at the start of each billing cycle;</LI><LI>subscription pricing, included quotas, and plan benefits may change prospectively;</LI><LI>some features may remain unavailable, limited, beta, experimental, or usage-capped even on paid plans.</LI></UL><P>If you cancel a subscription, your paid subscription access may continue until the end of the then-current billing period, unless earlier suspended or terminated under these Terms.</P></S>

      <S><H2>9. Add-On Analyses</H2><P>We may offer one-time purchases of additional analyses or other digital entitlements.</P><P>Unless otherwise stated:</P><UL><LI>add-on analyses are separate from subscription-included monthly analyses;</LI><LI>add-on analyses are consumed only after included monthly analyses are exhausted, if applicable;</LI><LI>add-on analyses are non-refundable once granted, except where required by law or expressly stated by us or the Merchant of Record;</LI><LI>add-on analyses may remain associated with your account after cancellation of a subscription, subject to your continued compliance with these Terms and continued availability of the Service.</LI></UL><P>We may modify or discontinue add-on offerings at any time.</P></S>

      <S><H2>10. Payments and Merchant of Record</H2><P>Payments are processed by our Merchant of Record and payment partner, including Paddle or its affiliates/processors, which may handle billing, subscriptions, taxes, invoicing, payment processing, and certain refund workflows.</P><P>You authorize the Merchant of Record to charge the payment method you provide for:</P><UL><LI>subscriptions,</LI><LI>renewals,</LI><LI>add-ons,</LI><LI>applicable taxes,</LI><LI>and any other amounts you expressly agree to pay.</LI></UL><P>We do not directly store full payment card information.</P><P>Your purchase may also be subject to the Merchant of Record&apos;s terms, billing flows, and payment rules.</P></S>

      <S><H2>11. Refunds, Renewals, and Cancellation</H2><P>Except where required by applicable law, all purchases are final.</P><P>Without limiting the foregoing:</P><UL><LI>used analyses are non-refundable;</LI><LI>partially used billing periods are non-refundable;</LI><LI>unused included monthly analyses do not roll over and do not create any cash refund right;</LI><LI>add-on analyses, once granted, are non-refundable except where required by law or expressly approved;</LI><LI>cancellation stops future renewals, but does not retroactively undo charges already incurred.</LI></UL><P>You are responsible for managing your subscription and cancellation before the next renewal date.</P></S>

      <S><H2>12. EU / EEA Digital Content and Immediate Performance</H2><P>If you are a consumer in the EU/EEA or another jurisdiction that grants a statutory withdrawal right for digital content or digital services, you expressly request immediate performance of the Service where applicable and acknowledge that, once immediate performance begins in circumstances permitted by law, you may lose or limit your withdrawal right to the extent allowed by applicable law.</P><P>If mandatory consumer law in your jurisdiction gives you rights that cannot be waived, nothing in these Terms limits those rights.</P></S>

      <S><H2>13. Accounts, Access, and Security</H2><P>Some features may require an account. Some limited features may be available without an account.</P><P>You are responsible for:</P><UL><LI>providing accurate account information,</LI><LI>maintaining the confidentiality of your login credentials,</LI><LI>all activity that occurs under your account,</LI><LI>and ensuring your device, browser, email, and authentication methods remain secure.</LI></UL><P>We may require identity verification, email verification, anti-abuse checks, or account creation before allowing access to some or all features.</P><P>You must promptly notify us if you believe your account has been compromised.</P></S>

      <S><H2>14. Acceptable Use</H2><P>You agree not to, and not to assist or permit others to:</P><UL><LI>bypass or attempt to bypass plan restrictions, analysis limits, gates, paywalls, or rate limits;</LI><LI>automate abusive requests or use bots, scripts, or scraping tools in a manner that abuses the Service;</LI><LI>attempt prompt injection, model extraction, data extraction, jailbreaking, or adversarial manipulation of the Service;</LI><LI>reverse engineer, copy, mirror, frame, or reproduce the Service except as expressly allowed by law;</LI><LI>use the Service to build a competing product using outputs, product behavior, prompts, or system design learned from the Service;</LI><LI>use the Service for unlawful, infringing, defamatory, fraudulent, deceptive, harmful, or abusive purposes;</LI><LI>interfere with the security, stability, or operation of the Service;</LI><LI>resell, sublicense, or commercially exploit the Service or outputs in violation of these Terms.</LI></UL><P>We may investigate suspected abuse and take any action we deem appropriate, including throttling, suspension, termination, data removal, analysis invalidation, forfeiture of entitlements, blocking of future purchases, and legal reporting.</P></S>

      <S><H2>15. Inputs and Outputs</H2><P>You retain responsibility for the prompts, inputs, data, documents, or other content you submit to the Service (&ldquo;Inputs&rdquo;).</P><P>You represent and warrant that you have all rights, permissions, and lawful bases necessary to submit your Inputs and use them with the Service.</P><P>You are solely responsible for ensuring that your Inputs and your use of Outputs do not violate any law, contract, confidentiality obligation, privacy right, intellectual property right, or third-party right.</P><P>To operate, maintain, secure, improve, and provide the Service, you grant us a non-exclusive, worldwide, royalty-free license to host, process, transmit, store, analyze, and use your Inputs and Outputs for the limited purposes of providing and improving the Service, enforcing these Terms, preventing abuse, complying with law, and maintaining system reliability.</P></S>

      <S><H2>16. Data, Analytics, and Abuse Prevention</H2><P>We may collect, store, and process:</P><UL><LI>account information,</LI><LI>usage metadata,</LI><LI>device or browser information,</LI><LI>IP addresses,</LI><LI>logs,</LI><LI>prompts and Inputs,</LI><LI>generated Outputs,</LI><LI>purchase and subscription status,</LI><LI>and abuse-prevention signals.</LI></UL><P>We may use this data to:</P><UL><LI>provide the Service,</LI><LI>enforce quotas and access rules,</LI><LI>detect fraud or abuse,</LI><LI>debug and improve product quality,</LI><LI>maintain service integrity,</LI><LI>and comply with legal obligations.</LI></UL><P>For more information, see our Privacy Policy.</P></S>

      <S><H2>17. Saved Reports, Exports, and Data Retention</H2><P>Saved reports, exports, PDFs, and account history may be available only on certain plans or only while features remain supported.</P><P>We do not guarantee that any report, export, saved result, or historical data will remain available indefinitely.</P><P>We may delete or disable access to saved materials due to:</P><UL><LI>plan changes,</LI><LI>account changes,</LI><LI>storage limits,</LI><LI>abuse prevention,</LI><LI>technical migration,</LI><LI>product changes,</LI><LI>legal requirements,</LI><LI>or discontinuation of features.</LI></UL><P>You are responsible for exporting or backing up any information you want to retain.</P></S>

      <S><H2>18. Beta, Experimental, and Changing Features</H2><P>Some features may be beta, experimental, preview, or under active development.</P><P>We may change, suspend, limit, redesign, or discontinue any part of the Service at any time, including:</P><UL><LI>pricing,</LI><LI>subscriptions,</LI><LI>analysis quotas,</LI><LI>free limits,</LI><LI>models used,</LI><LI>output format,</LI><LI>APIs,</LI><LI>tabs or sections,</LI><LI>exports,</LI><LI>saved reports,</LI><LI>and any product flow.</LI></UL><P>We have no obligation to continue any feature, plan, or capability.</P></S>

      <S><H2>19. Service Availability</H2><P>The Service is provided on an &ldquo;as is&rdquo; and &ldquo;as available&rdquo; basis.</P><P>We do not guarantee that the Service will be:</P><UL><LI>uninterrupted,</LI><LI>error-free,</LI><LI>secure,</LI><LI>accurate,</LI><LI>available at any specific time,</LI><LI>or compatible with any specific device, browser, or use case.</LI></UL><P>Outages, errors, delays, degraded quality, rate limits, third-party failures, model changes, vendor outages, or API disruptions may occur at any time.</P></S>

      <S><H2>20. Disclaimer of Warranties</H2><P>To the maximum extent permitted by law, we disclaim all warranties, whether express, implied, statutory, or otherwise, including any implied warranties of:</P><UL><LI>merchantability,</LI><LI>fitness for a particular purpose,</LI><LI>non-infringement,</LI><LI>accuracy,</LI><LI>availability,</LI><LI>title,</LI><LI>quiet enjoyment,</LI><LI>and satisfactory quality.</LI></UL><P>We do not warrant that the Service or any Output will meet your expectations or requirements.</P></S>

      <S><H2>21. Limitation of Liability</H2><P>To the maximum extent permitted by law:</P><UL><LI>we are not liable for any indirect, incidental, consequential, special, exemplary, or punitive damages;</LI><LI>we are not liable for lost profits, lost revenue, lost business, lost opportunities, loss of goodwill, loss of data, or business interruption;</LI><LI>we are not liable for decisions made, opportunities pursued, money spent, code built, products launched, contracts entered into, or business actions taken in reliance on the Service or any Output;</LI><LI>we are not liable for third-party services, payment processors, hosting providers, model providers, search providers, or vendor failures;</LI><LI>we are not liable for account loss, saved report loss, export loss, or feature discontinuation.</LI></UL><P>To the maximum extent permitted by law, our total aggregate liability arising out of or relating to the Service or these Terms shall not exceed the greater of:</P><OL><LI>the amount you paid to us through the Merchant of Record for the Service in the 30 days before the event giving rise to the claim; or</LI><LI>USD 50.</LI></OL><P>Some jurisdictions do not allow certain limitations, so some of the above may not apply to you to the extent prohibited by law.</P></S>

      <S><H2>22. Indemnification</H2><P>You agree to defend, indemnify, and hold harmless us, our operators, contractors, service providers, affiliates, and agents from and against any claims, liabilities, damages, losses, costs, and expenses (including reasonable legal fees) arising out of or related to:</P><UL><LI>your Inputs,</LI><LI>your Outputs or your use of Outputs,</LI><LI>your use or misuse of the Service,</LI><LI>your violation of these Terms,</LI><LI>your violation of law,</LI><LI>or your violation of any third-party rights.</LI></UL></S>

      <S><H2>23. Suspension and Termination</H2><P>We may suspend, restrict, downgrade, or terminate your access to all or part of the Service at any time, with or without notice, if:</P><UL><LI>we suspect abuse, fraud, automation abuse, or evasion of limits;</LI><LI>you violate these Terms;</LI><LI>payment fails or is reversed;</LI><LI>required by law, security, or vendor obligations;</LI><LI>or we decide to discontinue the Service or part of it.</LI></UL><P>Upon suspension or termination, some or all of your access, analyses, saved reports, exports, or account data may be limited or lost.</P><P>We are not obligated to restore access, analyses, or materials after termination, except where required by law.</P></S>

      <S><H2>24. Intellectual Property</H2><P>The Service, including its software, interface, visual design, branding, product flows, prompts, compilations, arrangement of content, and related materials, is owned by us or our licensors and is protected by applicable intellectual property laws.</P><P>These Terms do not grant you any ownership rights in the Service.</P><P>You may use the Service only as expressly permitted by these Terms.</P></S>

      <S><H2>25. Governing Law</H2><P>These Terms are governed by the laws of Türkiye, excluding conflict-of-laws principles, except to the extent mandatory consumer protection laws in your jurisdiction require otherwise.</P></S>

      <S><H2>26. Disputes</H2><P>To the maximum extent permitted by law:</P><UL><LI>any dispute, claim, or controversy arising out of or relating to these Terms or the Service shall be brought on an individual basis only;</LI><LI>you waive any right to participate in a class action, class arbitration, or representative proceeding;</LI><LI>disputes shall be submitted to the competent courts of Türkiye, unless mandatory law in your jurisdiction provides otherwise.</LI></UL><P>Nothing in this section limits any non-waivable rights you may have under applicable consumer law.</P></S>

      <S><H2>27. Changes to These Terms</H2><P>We may update these Terms at any time.</P><P>The updated version becomes effective when posted, unless otherwise stated.</P><P>Your continued use of the Service after updated Terms become effective constitutes acceptance of the updated Terms.</P></S>

      <S><H2>28. Severability</H2><P>If any provision of these Terms is held invalid, illegal, or unenforceable, the remaining provisions will remain in full force and effect to the maximum extent permitted by law.</P></S>

      <S><H2>29. Entire Agreement</H2><P>These Terms, together with any policies or additional terms expressly incorporated by reference, constitute the entire agreement between you and us regarding the Service and supersede prior or contemporaneous understandings relating to the Service.</P></S>

      <S><H2>30. Contact</H2><P>For questions regarding these Terms, contact:</P><P><A href="mailto:builder@unbuilt.me">builder@unbuilt.me</A></P></S>
    </>
  );
}
