const S = ({ children, style, ...props }: React.HTMLAttributes<HTMLElement> & { as?: string }) => (
  <section style={{ marginBottom: "2.5rem", ...style }} {...props}>{children}</section>
);
const H2 = ({ children }: { children: React.ReactNode }) => (
  <h2 style={{ fontSize: 20, fontWeight: 600, color: "#fff", marginBottom: "0.75rem", letterSpacing: "-0.01em" }}>{children}</h2>
);
const H3 = ({ children }: { children: React.ReactNode }) => (
  <h3 style={{ fontSize: 16, fontWeight: 600, color: "#ddd", marginBottom: "0.5rem" }}>{children}</h3>
);
const P = ({ children }: { children: React.ReactNode }) => (
  <p style={{ color: "#bbb", marginBottom: "0.75rem" }}>{children}</p>
);
const UL = ({ children }: { children: React.ReactNode }) => (
  <ul style={{ color: "#bbb", paddingLeft: "1.25rem", marginBottom: "0.75rem", listStyleType: "disc" }}>{children}</ul>
);
const LI = ({ children }: { children: React.ReactNode }) => (
  <li style={{ marginBottom: "0.35rem" }}>{children}</li>
);

export default function PrivacyPolicyPage() {
  return (
    <>
      <S>
        <P>
          Unbuilt (&quot;we&quot;, &quot;us&quot;, &quot;our&quot;) operates the Unbuilt market research platform. This Privacy Policy explains what data we collect, how we use it, and what we store when you use our service.
        </P>
      </S>

      <S>
        <H2>1. Information We Collect</H2>

        <H3>Account Information</H3>
        <P>
          When you create an account, we collect your email address and basic profile information through our authentication provider, Clerk. This information is used solely for account management and authentication.
        </P>

        <H3>Queries and Analysis Reports</H3>
        <P>
          When you run a Dig or Stack analysis, we store the following in our database:
        </P>
        <UL>
          <LI>The idea or niche you submitted (your prompt)</LI>
          <LI>The full analysis report generated by our AI (including all sections, scores, competitor data, and recommendations)</LI>
          <LI>The tool used (Dig or Stack)</LI>
          <LI>Your account ID and the timestamp of the query</LI>
        </UL>
        <P>
          This data is stored so that you can access your past reports at any time from the My Reports section. It is also used by us internally to monitor service quality and improve the platform.
        </P>

        <H3>Usage Data</H3>
        <P>We also collect general usage information including:</P>
        <UL>
          <LI>Features and tools you use</LI>
          <LI>Timestamps and frequency of usage</LI>
          <LI>Device type and browser information</LI>
        </UL>
      </S>

      <S>
        <H2>2. What We Can See</H2>
        <P>
          As the operators of this service, we have access to the ideas and prompts you submit, as well as the full AI-generated reports stored in our database. We may review this data to improve the service, debug issues, or monitor for abuse. We do not share this content with third parties for commercial purposes.
        </P>
        <P>
          If you have concerns about submitting sensitive or confidential business ideas, please be aware of this before using the service.
        </P>
      </S>

      <S>
        <H2>3. Third-Party Services and APIs</H2>
        <P>To provide market analysis, we integrate with the following third-party services:</P>
        <UL>
          <LI><strong style={{ color: "#ddd" }}>Anthropic API (Claude Opus)</strong> — AI-powered market analysis using extended thinking</LI>
          <LI><strong style={{ color: "#ddd" }}>Apple iTunes Search API</strong> — App Store data for competitor analysis</LI>
          <LI><strong style={{ color: "#ddd" }}>Google Play</strong> — Android app market data</LI>
          <LI><strong style={{ color: "#ddd" }}>YouTube Data API</strong> — Video content and trend analysis</LI>
          <LI><strong style={{ color: "#ddd" }}>Reddit, X (Twitter), LinkedIn</strong> — Public community signals and discussions</LI>
          <LI><strong style={{ color: "#ddd" }}>Product Hunt API</strong> — Product launch and community data</LI>
          <LI><strong style={{ color: "#ddd" }}>Clerk</strong> — User authentication and account management</LI>
          <LI><strong style={{ color: "#ddd" }}>Supabase</strong> — Database storage for reports and credits</LI>
          <LI><strong style={{ color: "#ddd" }}>Paddle</strong> — Payment processing for credit purchases</LI>
        </UL>
        <P>
          Your search queries are sent to these services to generate analysis results. Anthropic&apos;s API does not use your inputs to train its models. Each third-party service has its own privacy policy governing how they handle data.
        </P>
      </S>

      <S>
        <H2>4. How We Use Your Information</H2>
        <UL>
          <LI>To provide and maintain the Unbuilt service</LI>
          <LI>To authenticate your account and manage sessions</LI>
          <LI>To generate and store market research reports based on your queries</LI>
          <LI>To allow you to access your past reports via My Reports</LI>
          <LI>To improve the quality and accuracy of our analysis</LI>
          <LI>To process payments and manage credits</LI>
          <LI>To communicate important service updates</LI>
        </UL>
      </S>

      <S>
        <H2>5. Data Sharing</H2>
        <P>
          <strong style={{ color: "#fff" }}>We do not sell your personal data.</strong> We do not share your prompts, ideas, or report contents with third parties for advertising or marketing purposes. Your data is only shared with the third-party infrastructure services listed above to the extent technically necessary to run the platform.
        </P>
      </S>

      <S>
        <H2>6. Data Retention</H2>
        <P>
          Your account information is retained for as long as your account is active. Analysis reports (your prompts and the full AI-generated output) are retained for <strong style={{ color: "#ddd" }}>12 months</strong> from the date they were created, after which they are deleted automatically.
        </P>
        <P>
          You may request deletion of your data at any time — before the 12-month period expires — by emailing{" "}
          <a href="mailto:builder@unbuilt.me" style={{ color: "#888", textDecoration: "underline", textUnderlineOffset: 3 }}>builder@unbuilt.me</a>{" "}
          with your request. We will process deletion requests within 30 days.
        </P>
      </S>

      <S>
        <H2>7. Data Security</H2>
        <P>
          We store your data in Supabase, a managed cloud database with row-level security enabled. Access to the database is restricted to authorized service accounts only. We implement appropriate technical measures to protect your data against unauthorized access. However, no method of transmission over the internet is 100% secure.
        </P>
      </S>

      <S>
        <H2>8. Your Rights</H2>
        <P>You have the right to:</P>
        <UL>
          <LI>Access the data we hold about you — your reports are visible in the My Reports section</LI>
          <LI>Request deletion of your account and all associated data</LI>
          <LI>Request correction of inaccurate account information</LI>
          <LI>Export your data in a portable format</LI>
          <LI>Withdraw consent for data processing</LI>
        </UL>
        <P>
          To exercise any of these rights, contact us at{" "}
          <a href="mailto:builder@unbuilt.me" style={{ color: "#888", textDecoration: "underline", textUnderlineOffset: 3 }}>builder@unbuilt.me</a>.
        </P>
      </S>

      <S>
        <H2>9. Changes to This Policy</H2>
        <P>
          We may update this Privacy Policy from time to time. We will notify you of any material changes by posting the new policy on this page and updating the &quot;Last updated&quot; date.
        </P>
      </S>

      <S>
        <H2>10. Contact</H2>
        <P>
          If you have any questions about this Privacy Policy, please contact us at{" "}
          <a href="mailto:builder@unbuilt.me" style={{ color: "#888", textDecoration: "underline", textUnderlineOffset: 3 }}>builder@unbuilt.me</a>.
        </P>
      </S>
    </>
  );
}
