const S = ({ children }: { children: React.ReactNode }) => (
  <section style={{ marginBottom: "2.5rem" }}>{children}</section>
);
const H2 = ({ children }: { children: React.ReactNode }) => (
  <h2 style={{ fontSize: 20, fontWeight: 600, color: "#fff", marginBottom: "0.75rem", letterSpacing: "-0.01em" }}>{children}</h2>
);
const P = ({ children }: { children: React.ReactNode }) => (
  <p style={{ color: "#bbb", marginBottom: "0.75rem" }}>{children}</p>
);
const UL = ({ children }: { children: React.ReactNode }) => (
  <ul style={{ color: "#bbb", paddingLeft: "1.25rem", marginBottom: "0.75rem", listStyleType: "disc" }}>{children}</ul>
);
const LI = ({ children }: { children: React.ReactNode }) => (
  <li style={{ marginBottom: "0.35rem" }}>{children}</li>
);

export default function DisclaimerPage() {
  return (
    <>
      <S>
        <div style={{
          background: "#1a1200",
          border: "1px solid #332800",
          borderRadius: 8,
          padding: "1rem 1.25rem",
          marginBottom: "1.5rem",
        }}>
          <p style={{ color: "#d4a800", marginBottom: 0, fontWeight: 500 }}>
            All content on Unbuilt is generated by artificial intelligence and aggregated from public data sources. It is provided for informational and research purposes only. Nothing on this platform constitutes professional advice.
          </p>
        </div>
      </S>

      <S>
        <H2>1. No Financial Advice</H2>
        <P>
          Unbuilt does not provide financial, investment, or business valuation advice. Market scores, opportunity assessments, and competitive analyses are algorithmic estimations based on publicly available data. They should not be used as the sole basis for investment decisions, business acquisitions, or financial planning.
        </P>
      </S>

      <S>
        <H2>2. No Legal Advice</H2>
        <P>
          Nothing on this platform constitutes legal advice. Discussions of market regulations, intellectual property, or compliance requirements in AI-generated analyses are general observations and should not replace consultation with a qualified attorney.
        </P>
      </S>

      <S>
        <H2>3. Accuracy of Information</H2>
        <P>While we strive for accuracy, we cannot guarantee that all information is correct, complete, or up-to-date:</P>
        <UL>
          <LI><strong style={{ color: "#ddd" }}>App Store data</strong> may not reflect the most recent updates, removals, or rating changes</LI>
          <LI><strong style={{ color: "#ddd" }}>Market scores</strong> are computed from limited public signals and may not capture the full picture</LI>
          <LI><strong style={{ color: "#ddd" }}>AI analysis</strong> may contain inaccuracies, hallucinations, or outdated information</LI>
          <LI><strong style={{ color: "#ddd" }}>Competitor data</strong> may be incomplete, especially for private companies or stealth startups</LI>
        </UL>
      </S>

      <S>
        <H2>4. Third-Party Data</H2>
        <P>
          Unbuilt aggregates data from third-party sources including Apple App Store, Google Play, Product Hunt, GitHub, and YouTube. We do not control or verify the accuracy of data from these sources. Changes to third-party APIs may affect the availability or accuracy of our analysis at any time.
        </P>
      </S>

      <S>
        <H2>5. Use at Your Own Risk</H2>
        <P>
          The service is provided &quot;as is&quot; and &quot;as available&quot; without warranties of any kind, either express or implied. You use Unbuilt at your own risk. We disclaim all warranties, including but not limited to:
        </P>
        <UL>
          <LI>Merchantability or fitness for a particular purpose</LI>
          <LI>Accuracy, reliability, or completeness of any analysis</LI>
          <LI>Uninterrupted or error-free operation of the service</LI>
          <LI>Results or outcomes from acting on AI-generated insights</LI>
        </UL>
      </S>

      <S>
        <H2>6. Limitation of Liability</H2>
        <P>
          To the maximum extent permitted by applicable law, Unbuilt and its creators shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of or reliance on the service, including but not limited to loss of profits, data, business opportunities, or goodwill.
        </P>
      </S>

      <S>
        <H2>7. Independent Verification</H2>
        <P>
          We strongly encourage users to independently verify all insights and data before making business decisions. Unbuilt is a research starting point, not a substitute for thorough due diligence, professional consulting, or domain expertise.
        </P>
      </S>

      <S>
        <H2>8. Contact</H2>
        <P>
          Questions about this disclaimer? Contact us at{" "}
          <a href="mailto:builder@unbuilt.me" style={{ color: "#888", textDecoration: "underline", textUnderlineOffset: 3 }}>builder@unbuilt.me</a>.
        </P>
      </S>
    </>
  );
}
