const S = ({ children }: { children: React.ReactNode }) => (
  <section style={{ marginBottom: "2.5rem" }}>{children}</section>
);
const H2 = ({ children }: { children: React.ReactNode }) => (
  <h2 style={{ fontSize: 20, fontWeight: 600, color: "var(--clr-text)", marginBottom: "0.75rem", letterSpacing: "-0.01em" }}>{children}</h2>
);
const P = ({ children }: { children: React.ReactNode }) => (
  <p style={{ color: "var(--clr-text)", marginBottom: "0.75rem" }}>{children}</p>
);
const UL = ({ children }: { children: React.ReactNode }) => (
  <ul style={{ paddingLeft: "1.5rem", marginBottom: "0.75rem", color: "var(--clr-text)", lineHeight: 1.8 }}>{children}</ul>
);
const LI = ({ children }: { children: React.ReactNode }) => <li>{children}</li>;
const B = ({ children }: { children: React.ReactNode }) => <strong style={{ fontWeight: 600 }}>{children}</strong>;
const A = ({ href, children }: { href: string; children: React.ReactNode }) => (
  <a href={href} style={{ color: "var(--clr-accent)", textDecoration: "underline" }}>{children}</a>
);

export default function DisclaimerPage() {
  return (
    <>
      <S>
        <H2>1. General Information</H2>
        <P>The information and outputs provided by unbuilt.me are for general informational purposes only.</P>
      </S>
      <S>
        <H2>2. AI-Generated Content</H2>
        <P>All outputs are generated by artificial intelligence.</P>
        <P>We do not guarantee that outputs are:</P>
        <UL>
          <LI>accurate</LI>
          <LI>complete</LI>
          <LI>reliable</LI>
          <LI>up to date</LI>
        </UL>
      </S>
      <S>
        <H2>3. No Professional Advice</H2>
        <P>The Service does not provide:</P>
        <UL>
          <LI>financial advice</LI>
          <LI>legal advice</LI>
          <LI>investment advice</LI>
          <LI>business guarantees</LI>
        </UL>
        <P>You should not rely on the Service for critical decisions.</P>
      </S>
      <S>
        <H2>4. Use at Your Own Risk</H2>
        <P>You agree that:</P>
        <UL>
          <LI>you use the Service at your own risk</LI>
          <LI>you are solely responsible for any decisions or actions taken based on outputs</LI>
        </UL>
      </S>
      <S>
        <H2>5. Business & Financial Risk</H2>
        <P>We are not responsible for:</P>
        <UL>
          <LI>business outcomes</LI>
          <LI>financial losses</LI>
          <LI>failed projects</LI>
          <LI>incorrect strategic decisions</LI>
        </UL>
      </S>
      <S>
        <H2>6. Third-Party Data</H2>
        <P>The Service may rely on external data sources and APIs.</P>
        <P>We do not guarantee the accuracy or reliability of third-party data.</P>
      </S>
      <S>
        <H2>7. No Warranty</H2>
        <P>The Service is provided <B>"as is"</B> and <B>"as available"</B>.</P>
        <P>We make no warranties, express or implied.</P>
      </S>
      <S>
        <H2>8. Limitation Reminder</H2>
        <P>This Disclaimer should be read together with the Terms of Service.</P>
        <P>In case of conflict, the Terms of Service prevail.</P>
      </S>
      <S>
        <H2>9. Contact</H2>
        <P><A href="mailto:builder@unbuilt.me">builder@unbuilt.me</A></P>
      </S>
    </>
  );
}