const S = ({ children }: { children: React.ReactNode }) => (
  <section style={{ marginBottom: "2.5rem" }}>{children}</section>
);
const H2 = ({ children }: { children: React.ReactNode }) => (
  <h2 style={{ fontSize: 20, fontWeight: 600, color: "var(--clr-text)", marginBottom: "0.75rem", letterSpacing: "-0.01em" }}>{children}</h2>
);
const P = ({ children }: { children: React.ReactNode }) => (
  <p style={{ color: "var(--clr-text)", marginBottom: "0.75rem" }}>{children}</p>
);
const UL = ({ children }: { children: React.ReactNode }) => (
  <ul style={{ paddingLeft: "1.5rem", marginBottom: "0.75rem", color: "var(--clr-text)", lineHeight: 1.8 }}>{children}</ul>
);
const LI = ({ children }: { children: React.ReactNode }) => <li>{children}</li>;
const A = ({ href, children }: { href: string; children: React.ReactNode }) => (
  <a href={href} style={{ color: "var(--clr-accent)", textDecoration: "underline" }}>{children}</a>
);

export default function AITransparencyPage() {
  return (
    <>
      <S><H2>1. Overview</H2><P>unbuilt.me (the &ldquo;Service&rdquo;) uses artificial intelligence, automated systems, and third-party model providers to generate analyses, reports, recommendations, summaries, stack suggestions, product guidance, and other outputs.</P><P>These outputs are generated automatically in response to user inputs and system instructions.</P><P>The Service is designed to assist with exploration and decision support. It is not a source of guaranteed truth, professional advice, or verified factual conclusions.</P></S>

      <S><H2>2. How the System Works</H2><P>The Service may process and combine:</P><UL><LI>user-provided prompts, ideas, and other Inputs,</LI><LI>system instructions and internal prompt logic,</LI><LI>model outputs generated by third-party AI providers,</LI><LI>search or enrichment data from third-party providers,</LI><LI>internal formatting, gating, scoring, or presentation logic,</LI><LI>account or plan status that determines which output depth is shown.</LI></UL><P>Outputs are generated probabilistically and are not deterministic. The same or similar input may produce different outputs at different times.</P></S>

      <S><H2>3. Free vs Paid Output</H2><P>The Service may provide different output depth depending on plan type, usage status, feature access, or whether an analysis is generated through a free or paid flow.</P><P>For example:</P><UL><LI>free users may receive limited, reduced-depth, lower-cost, or gated output;</LI><LI>paid users may receive broader, deeper, or higher-cost output;</LI><LI>users who exhaust included usage may fall back to limited output modes.</LI></UL><P>These differences are part of the product design and do not imply that any output is complete, comprehensive, authoritative, or guaranteed.</P></S>

      <S><H2>4. What AI Can and Cannot Do</H2><P>AI systems can identify patterns, summarize information, generate structured analysis, and produce useful suggestions.</P><P>However, AI systems also have important limitations.</P><P>AI-generated outputs may be:</P><UL><LI>incorrect,</LI><LI>incomplete,</LI><LI>inconsistent,</LI><LI>misleading,</LI><LI>outdated,</LI><LI>oversimplified,</LI><LI>speculative,</LI><LI>or poorly calibrated for your specific situation.</LI></UL><P>AI systems may:</P><UL><LI>hallucinate facts or sources,</LI><LI>overstate confidence,</LI><LI>miss key context,</LI><LI>misread niche markets,</LI><LI>reflect biases in training data or retrieved information,</LI><LI>or produce outputs that sound convincing while still being wrong.</LI></UL><P>You must not treat AI output as automatically true, verified, complete, or suitable for high-stakes reliance.</P></S>

      <S><H2>5. No Professional Advice</H2><P>The Service does not provide:</P><UL><LI>legal advice,</LI><LI>financial advice,</LI><LI>tax advice,</LI><LI>investment advice,</LI><LI>accounting advice,</LI><LI>employment advice,</LI><LI>medical advice,</LI><LI>or any other regulated professional advice.</LI></UL><P>Nothing in the Service should be interpreted as a recommendation to invest, launch, buy, sell, hire, fire, enter into contracts, form a company, choose a legal structure, or take any high-stakes business or legal action without your own independent review and, where appropriate, professional advice.</P></S>

      <S><H2>6. No Guarantee of Accuracy or Results</H2><P>We do not guarantee that any output is:</P><UL><LI>accurate,</LI><LI>complete,</LI><LI>current,</LI><LI>reliable,</LI><LI>unbiased,</LI><LI>merchantable,</LI><LI>fit for a particular purpose,</LI><LI>or suitable for your business, product, market, or legal/commercial decisions.</LI></UL><P>We do not guarantee:</P><UL><LI>that an idea score is correct,</LI><LI>that a recommendation is sound,</LI><LI>that a market gap is real,</LI><LI>that a competitor assessment is complete,</LI><LI>that a suggested stack is optimal,</LI><LI>or that following an output will produce any commercial result.</LI></UL><P>The Service is not a guarantee engine, predictive certainty system, or substitute for validation in the real world.</P></S>

      <S><H2>7. Third-Party AI and Data Providers</H2><P>We rely on third-party providers to generate and enrich outputs. These may include, depending on product configuration over time:</P><UL><LI>AI/model providers,</LI><LI>search or enrichment providers,</LI><LI>hosting and infrastructure providers,</LI><LI>and related service vendors.</LI></UL><P>Your inputs may be transmitted to and processed by such providers in order to generate outputs or operate the Service.</P><P>We do not control every aspect of how third-party systems generate results. We also do not guarantee uninterrupted availability, consistency, or quality from any third-party provider.</P></S>

      <S><H2>8. Search, Retrieval, and Knowledge Limits</H2><P>Some outputs may rely on:</P><UL><LI>model knowledge,</LI><LI>search-enriched data,</LI><LI>retrieved content,</LI><LI>or no external retrieval at all.</LI></UL><P>Accordingly:</P><UL><LI>some outputs may reflect older model knowledge rather than live data,</LI><LI>some outputs may be based on incomplete search or retrieval results,</LI><LI>some outputs may omit relevant competitors, market signals, risks, or context,</LI><LI>and some outputs may present partial information in a simplified or summarized way.</LI></UL><P>Even when external data is used, the Service does not guarantee that all relevant sources were found, interpreted correctly, or incorporated into the final result.</P></S>

      <S><H2>9. Scoring and Recommendation Limits</H2><P>Where the Service provides:</P><UL><LI>scores,</LI><LI>labels,</LI><LI>recommendations,</LI><LI>or action suggestions,</LI></UL><P>those are generated by automated systems using internal logic, scoring rules, and AI interpretation.</P><P>Such outputs are:</P><UL><LI>informational,</LI><LI>non-binding,</LI><LI>and not guarantees of business quality or commercial viability.</LI></UL><P>A low score does not prove an idea cannot work. A high score does not prove an idea will work. A recommendation is not a guarantee or instruction.</P></S>

      <S><H2>10. Transparency Limits</H2><P>AI systems and multi-step software systems are inherently complex.</P><P>Although we may describe some aspects of how the Service works, we do not guarantee full interpretability, traceability, or explainability for every output.</P><P>We may not be able to fully explain:</P><UL><LI>why a model chose a particular wording,</LI><LI>why a result differed from another run,</LI><LI>why a certain competitor was included or excluded,</LI><LI>or why a score changed after model, prompt, search, or product updates.</LI></UL><P>You acknowledge that full output traceability may not be available.</P></S>

      <S><H2>11. Continuous Changes and Improvement</H2><P>We continuously test, refine, and change the Service.</P><P>That may include changes to:</P><UL><LI>prompts,</LI><LI>scoring presentation,</LI><LI>models,</LI><LI>routing,</LI><LI>retrieval logic,</LI><LI>output structure,</LI><LI>plan entitlements,</LI><LI>free vs paid depth,</LI><LI>and product flows.</LI></UL><P>As a result:</P><UL><LI>outputs may change over time,</LI><LI>the same idea may receive different wording or structure later,</LI><LI>and historical outputs may not match future outputs.</LI></UL><P>Improvement does not guarantee correctness.</P></S>

      <S><H2>12. Your Responsibility</H2><P>You are solely responsible for:</P><UL><LI>evaluating outputs critically,</LI><LI>verifying important claims independently,</LI><LI>checking business, legal, financial, and market assumptions yourself,</LI><LI>testing ideas in the real world,</LI><LI>and deciding whether or how to act on any output.</LI></UL><P>You should not rely exclusively on the Service for any important decision.</P><P>At a minimum, you should:</P><UL><LI>sanity-check material claims,</LI><LI>validate important facts independently,</LI><LI>treat outputs as starting points, not final truth,</LI><LI>and consult qualified professionals where needed.</LI></UL></S>

      <S><H2>13. Sensitive and High-Stakes Use</H2><P>You should not use the Service as the sole basis for:</P><UL><LI>legal compliance,</LI><LI>securities or investment decisions,</LI><LI>regulated business advice,</LI><LI>tax strategy,</LI><LI>material contractual commitments,</LI><LI>or other high-stakes decisions.</LI></UL><P>If you choose to use the Service in those contexts, you do so entirely at your own risk.</P></S>

      <S><H2>14. Data Usage Related to AI Processing</H2><P>To provide AI features, we may process your inputs and outputs through internal systems and third-party providers.</P><P>We do not sell your data for third-party advertising.</P><P>We may process inputs and outputs to:</P><UL><LI>generate results,</LI><LI>maintain account history or saved reports,</LI><LI>improve service performance and reliability,</LI><LI>investigate abuse or misuse,</LI><LI>debug product issues,</LI><LI>and enforce our Terms and access rules.</LI></UL><P>For more detail, see our Privacy Policy.</P></S>

      <S><H2>15. No Duty to Monitor or Correct</H2><P>We have no obligation to:</P><UL><LI>manually review every output,</LI><LI>fact-check every analysis,</LI><LI>correct every inaccuracy,</LI><LI>or monitor how you use outputs.</LI></UL><P>We may improve the system over time, but we do not undertake a legal duty to supervise, certify, endorse, or correct outputs for your individual use case.</P></S>

      <S><H2>16. Contact</H2><P>If you have questions about this AI Transparency Policy, contact:</P><P><A href="mailto:builder@unbuilt.me">builder@unbuilt.me</A></P></S>
    </>
  );
}
