const S = ({ children }: { children: React.ReactNode }) => (
  <section style={{ marginBottom: "2.5rem" }}>{children}</section>
);
const H2 = ({ children }: { children: React.ReactNode }) => (
  <h2 style={{ fontSize: 20, fontWeight: 600, color: "#fff", marginBottom: "0.75rem", letterSpacing: "-0.01em" }}>{children}</h2>
);
const H3 = ({ children }: { children: React.ReactNode }) => (
  <h3 style={{ fontSize: 16, fontWeight: 600, color: "#ddd", marginBottom: "0.5rem" }}>{children}</h3>
);
const P = ({ children }: { children: React.ReactNode }) => (
  <p style={{ color: "#bbb", marginBottom: "0.75rem" }}>{children}</p>
);
const UL = ({ children }: { children: React.ReactNode }) => (
  <ul style={{ color: "#bbb", paddingLeft: "1.25rem", marginBottom: "0.75rem", listStyleType: "disc" }}>{children}</ul>
);
const LI = ({ children }: { children: React.ReactNode }) => (
  <li style={{ marginBottom: "0.35rem" }}>{children}</li>
);

export default function AITransparencyPage() {
  return (
    <>
      <S>
        <P>
          At Unbuilt, we believe in being transparent about how we use artificial intelligence. This page explains what AI does in our service, its limitations, and how we work to ensure responsible use.
        </P>
      </S>

      <S>
        <H2>1. How We Use AI</H2>
        <P>Unbuilt uses AI models provided by Anthropic (Claude) for the following purposes:</P>
        <UL>
          <LI><strong style={{ color: "#ddd" }}>Market Analysis</strong> — Synthesizing data from multiple sources into structured insights about market opportunities, competitors, and gaps</LI>
          <LI><strong style={{ color: "#ddd" }}>Sub-category Generation</strong> — Identifying relevant sub-niches within a broader market space</LI>
          <LI><strong style={{ color: "#ddd" }}>Opportunity Assessment</strong> — Evaluating potential business opportunities based on available data signals</LI>
          <LI><strong style={{ color: "#ddd" }}>Content Summarization</strong> — Condensing large amounts of market data into actionable summaries</LI>
        </UL>
      </S>

      <S>
        <H2>2. Data Sources</H2>
        <P>AI analysis in Unbuilt is informed by real data from multiple public sources:</P>

        <H3>App Store Data</H3>
        <P>We query the Apple iTunes Search API and Google Play to retrieve app listings, ratings, review counts, and release dates. This data is publicly available.</P>

        <H3>Product Hunt</H3>
        <P>We use the Product Hunt GraphQL API to identify recently launched products, their vote counts, and community reception.</P>

        <H3>Other Sources</H3>
        <P>Depending on the tool used, we may also query GitHub (open-source activity), YouTube (content trends), and search APIs for additional signals.</P>
      </S>

      <S>
        <H2>3. What AI Does NOT Do</H2>
        <UL>
          <LI>AI does not access private or proprietary databases</LI>
          <LI>AI does not make predictions about specific company financials or stock performance</LI>
          <LI>AI does not have access to real-time data beyond what our APIs provide</LI>
          <LI>AI does not store or learn from your individual queries across sessions</LI>
        </UL>
      </S>

      <S>
        <H2>4. Scoring Methodology</H2>
        <P>
          Market scores displayed in Trend Feed are <strong style={{ color: "#ddd" }}>calculated deterministically by our backend</strong>, not by AI. The score is based on measurable signals:
        </P>
        <UL>
          <LI>App store review counts (market size indicator)</LI>
          <LI>New app releases in the last 90 days (momentum indicator)</LI>
          <LI>Average ratings of new releases (quality signal)</LI>
          <LI>Product Hunt vote counts (innovation signal)</LI>
        </UL>
        <P>
          Market labels (e.g., &quot;Growing&quot;, &quot;Crowded&quot;, &quot;Uncharted&quot;) are also computed algorithmically from these data points, not generated by AI.
        </P>
      </S>

      <S>
        <H2>5. Limitations and Accuracy</H2>
        <P>AI-generated content has inherent limitations:</P>
        <UL>
          <LI><strong style={{ color: "#ddd" }}>Not real-time</strong> — AI model knowledge has a training cutoff date. Live data comes from our API integrations, not the AI itself.</LI>
          <LI><strong style={{ color: "#ddd" }}>Potential inaccuracies</strong> — AI may occasionally produce incorrect statements, especially about niche markets with limited public data.</LI>
          <LI><strong style={{ color: "#ddd" }}>Not exhaustive</strong> — Analysis covers publicly available data and may miss private companies, stealth startups, or emerging players.</LI>
          <LI><strong style={{ color: "#ddd" }}>Bias</strong> — AI models may reflect biases present in their training data, including geographic or language biases toward English-language markets.</LI>
        </UL>
      </S>

      <S>
        <H2>6. Human Oversight</H2>
        <P>
          We continuously review and refine our AI prompts, scoring algorithms, and data pipelines to improve accuracy. However, all AI output should be treated as a starting point for research, not a definitive answer. We encourage users to validate insights through their own research.
        </P>
      </S>

      <S>
        <H2>7. Your Data and AI</H2>
        <P>
          Your queries are sent to the Anthropic API to generate analysis. Anthropic&apos;s API does not use customer inputs to train models. Your queries are not stored by Anthropic beyond the duration needed to process the request. See{" "}
          <a href="/legal/privacy-policy" style={{ color: "#888", textDecoration: "underline", textUnderlineOffset: 3 }}>our Privacy Policy</a>{" "}
          for more details.
        </P>
      </S>

      <S>
        <H2>8. Contact</H2>
        <P>
          Questions about our AI practices? Contact us at{" "}
          <a href="mailto:builder@unbuilt.me" style={{ color: "#888", textDecoration: "underline", textUnderlineOffset: 3 }}>builder@unbuilt.me</a>.
        </P>
      </S>
    </>
  );
}
